name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Build
      run: |
        xcodebuild -project MoneyFlowLens.xcodeproj \
                   -scheme MoneyFlowLens \
                   -destination 'platform=macOS' \
                   build | xcpretty
