name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild \
            -project MoneyFlowLens.xcodeproj \
            -scheme MoneyFlowLens \
            -destination 'platform=macOS' \
            build
      - name: Archive
        run: |
          xcodebuild -scheme MoneyFlowLens -configuration Release -archivePath $PWD/MoneyFlowLens.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/MoneyFlowLens.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
      - name: Compress DMG
        run: hdiutil create MoneyFlowLens.dmg -srcfolder build
      - uses: actions/upload-artifact@v4
        with:
          name: MoneyFlowLens.dmg
          path: MoneyFlowLens.dmg
